### ISSUE TITLE
Add ability to connect to LDAP server via IPC

### ISSUE THREAD

**Issue by Dekedro** [ergochat/ergo-ldap#2]
Make it possible to use a socket as an address to the LDAP server.
Also known as ldapi://, present in the OpenLDAP and others.
Already supported by the underlying LDAP library.
[More info](https://web.archive.org/web/20220118065233/https://ldapwiki.com/wiki/Using%20LDAP%20over%20IPC%20Mechanisms)

**Comment by slingamn** [comment]
Resolved by #3
