### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by Dekedro** [ergochat/ergo-ldap#4]
Are there any blockers for tagging a release?

**Comment by slingamn** [comment]
No, but no very compelling reason to do so either, IMO. What are your thoughts?

**Comment by Dekedro** [comment]
Well, I would like to create package for this project as I believe ergo-ldap is reliable and useful enough.
Having a release would signal that to the others, thus making ergo-ldap easier to include into package repositories.
Just tagging `0.0.1` would be enough.

I do not expect any compatibility-between-versions promise.

**Comment by tacerus** [comment]
I also have this "issue" with the RPM package for ergo-ldap, currently I build it off the master branch with a Git version tag.

**Comment by slingamn** [comment]
Thanks for the feedback! Tagged https://github.com/ergochat/ergo-ldap/tree/v0.0.1 , no plans to upload release binaries though.
